version: "3.7"

services:


 nginx:
    image: nginx:1.19.8-alpine
    container_name: nginx
    restart: unless-stopped
    links:
      - api_backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - gstd2_network

 api_backend:
    build:
      args:
         user: ${USER}
         uid: 1000
      context: ./api_backend
      dockerfile: Dockerfile
    container_name: api_backend
    links:
       - master_db
    ports:
      - 9000:9000
    restart: unless-stopped
    working_dir: /var/www/html/
    tty: true
    volumes:
      - ./api_backend/src/:/var/www/html/
    networks:
     - gstd2_network

       
 cache_service:
  image: redis:latest 
  container_name: cache_service
  tty: true
  restart: unless-stopped
  command: redis-server --requirepass $CACHE_SERVER_PASSWORD
  ports:
    - "6379:6379"
  volumes:
    - cache_redis_data:/var/lib/redis
  networks:
    - gstd2_network


 master_db:
    image: postgres:12.5-alpine
    restart: unless-stopped
    container_name: master_db
    tty: true
    environment:
        POSTGRES_DB: $DB_USERNAME
        POSTGRES_USER: $DB_NAME
        POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - 5432:5432
    volumes:
     - master_data:/var/lib/postgresql/data/
    networks:
      - gstd2_network

 service_search:
      image: 'bitnami/elasticsearch:latest'
      container_name: service_search
      volumes:
        - elasticsearch:/usr/share/elasticsearch/data
      environment:
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "discovery.type=single-node"
      ports:
        - "9200:9200"
      networks:
        - gstd2_network

networks:
  gstd2_network:
    driver: bridge

volumes:
   master_data:
   www-html: 
   cache_redis_data:
   elasticsearch: 
